connect / as sysdba;
ALTER SESSION SET CONTAINER=ORCLPDB;
CREATE TABLESPACE fabtwin_data DATAFILE 'fabtwin_data01.dbf' SIZE 500M AUTOEXTEND ON NEXT 100M MAXSIZE 2G;
CREATE TEMPORARY TABLESPACE fabtwin_temp TEMPFILE 'fabtwin_temp01.dbf' SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE 500M;
CREATE USER fabtwin IDENTIFIED BY fabtwin DEFAULT TABLESPACE fabtwin_data TEMPORARY TABLESPACE fabtwin_temp;
GRANT CONNECT, RESOURCE, DBA TO fabtwin;
GRANT UNLIMITED TABLESPACE TO fabtwin;
exit;
