SET PAGESIZE 0 FEEDBACK OFF VERIFY OFF HEADING OFF ECHO OFF

-- Switch to PDB first
ALTER SESSION SET CONTAINER = ORCLPDB;

-- Drop existing local user in PDB
DROP USER fabtwin CASCADE;

-- Create local user in PDB
CREATE USER fabtwin IDENTIFIED BY fabtwin
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER TO fabtwin;
GRANT RESOURCE TO fabtwin;

-- Verify
SELECT 'SUCCESS: fabtwin user created in ORCLPDB' as status FROM dual;

EXIT;