SET LINESIZE 200
SET PAGESIZE 100

-- 检查 fabtwin 各表行数
SELECT table_name, num_rows
FROM user_tables
WHERE table_name IN (
  'AI_INSIGHTS','ALARMS','CHAMBER_SNAPSHOTS','DASHBOARD_KPI',
  'DT_ALARM_EVENT','DT_EVENT_RAW','DT_EVENT_RAW_CUR','DT_EVENT_STD',
  'DT_STATE_SNAPSHOT','EVENT_ACTION_MAPPINGS','FLOORS','FLOOR_AREAS',
  'LOTS','MACHINES','MACHINE_DIFY_CONFIGS','MACHINE_EVENTS',
  'MACHINE_MODEL_CONFIGS','MACHINE_TOOL_MAPPINGS','OHT_POSITIONS',
  'PERM_DATA','RECIPES','ROLES','ROLE_PERMISSIONS','TRACKS',
  'USERS','VEHICLES'
)
ORDER BY table_name;

-- 实际行数（num_rows 可能未更新，用 COUNT）
SELECT 'DT_EVENT_RAW' AS t, COUNT(*) AS cnt FROM dt_event_raw
UNION ALL SELECT 'DT_EVENT_RAW_CUR', COUNT(*) FROM dt_event_raw_cur
UNION ALL SELECT 'MACHINES', COUNT(*) FROM machines
UNION ALL SELECT 'LOTS', COUNT(*) FROM lots
UNION ALL SELECT 'ALARMS', COUNT(*) FROM alarms
UNION ALL SELECT 'MACHINE_EVENTS', COUNT(*) FROM machine_events
UNION ALL SELECT 'DT_STATE_SNAPSHOT', COUNT(*) FROM dt_state_snapshot;

EXIT;
