-- 在本机 fabtwin 用户下创建 OXE 相关 3 张 DT 表
-- （DDL 来自量产 EMUUSER schema，改 schema 为 fabtwin）
-- 用法: python run_init_sql.py create_oxe_dt_tables.sql

SET DEFINE OFF
SET SQLBLANKLINES ON

-- 清理旧表
DROP TABLE DT_RTLOT_TOOL_PORT_RULE CASCADE CONSTRAINTS PURGE;
DROP TABLE DT_RTLOT_EVENT_RULE CASCADE CONSTRAINTS PURGE;
DROP TABLE DT_EVENT_REALTIMELOT CASCADE CONSTRAINTS PURGE;

-- ============================================
-- 1. DT_EVENT_REALTIMELOT 实时 Lot 表
-- ============================================
CREATE TABLE DT_EVENT_REALTIMELOT (
    RT_ID             NUMBER NOT NULL,
    TOOL_ID           VARCHAR2(64) NOT NULL,
    PORT_ID           VARCHAR2(32) NOT NULL,
    LOT_KEY_MODE      VARCHAR2(32) DEFAULT 'SINGLE_LOT_PER_PORT' NOT NULL,
    LOT_BIZ_KEY       VARCHAR2(256) NOT NULL,
    LOT_ID            VARCHAR2(128),
    BATCH_ID          VARCHAR2(128),
    CASSETTE_ID       VARCHAR2(128),
    SMIF_ID           VARCHAR2(64),
    WAFER_MAPPING     CLOB,
    WAFER_ID          VARCHAR2(128),
    LAST_EVENT_NAME   VARCHAR2(64) NOT NULL,
    LAST_EVENT_TS_UTC TIMESTAMP(6),
    START_TS_UTC      TIMESTAMP(6),
    UPDATED_TS_UTC    TIMESTAMP(6) NOT NULL,
    SOURCE_SYSTEM     VARCHAR2(32) NOT NULL,
    SOURCE_MESSAGE_ID VARCHAR2(128) NOT NULL,
    ACTIVE_FLAG       CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_DT_EVENT_REALTIMELOT PRIMARY KEY (RT_ID)
);

ALTER TABLE DT_EVENT_REALTIMELOT ADD (
    CONSTRAINT UQ_DT_RTLOT_TOOL_PORT_LOTKEY
    UNIQUE (TOOL_ID, PORT_ID, LOT_BIZ_KEY)
);

ALTER TABLE DT_EVENT_REALTIMELOT ADD (
    CONSTRAINT CK_DT_RTLOT_KEY_MODE
    CHECK (LOT_KEY_MODE IN ('SINGLE_LOT_PER_PORT', 'MULTI_LOT_PER_PORT'))
);

ALTER TABLE DT_EVENT_REALTIMELOT ADD (
    CONSTRAINT CK_DT_RTLOT_ACTIVE
    CHECK (ACTIVE_FLAG IN ('Y', 'N'))
);

CREATE INDEX IDX_DT_RTLOT_TOOL_PORT_ACTIVE
    ON DT_EVENT_REALTIMELOT (TOOL_ID, PORT_ID, ACTIVE_FLAG);

COMMENT ON TABLE DT_EVENT_REALTIMELOT IS '实时Lot表：每条记录对应一个Tool/Port/LotKey';
COMMENT ON COLUMN DT_EVENT_REALTIMELOT.RT_ID IS '主键ID';
COMMENT ON COLUMN DT_EVENT_REALTIMELOT.TOOL_ID IS '机台ID';
COMMENT ON COLUMN DT_EVENT_REALTIMELOT.PORT_ID IS '端口ID（如LP1/LP2）';
COMMENT ON COLUMN DT_EVENT_REALTIMELOT.LOT_KEY_MODE IS 'Lot键模式：单Lot/多Lot';
COMMENT ON COLUMN DT_EVENT_REALTIMELOT.LOT_BIZ_KEY IS 'Lot业务键（唯一标识）';
COMMENT ON COLUMN DT_EVENT_REALTIMELOT.LAST_EVENT_NAME IS '最近事件名';
COMMENT ON COLUMN DT_EVENT_REALTIMELOT.ACTIVE_FLAG IS '是否活跃：Y/N';

-- ============================================
-- 2. DT_RTLOT_TOOL_PORT_RULE 端口规则表
-- ============================================
CREATE TABLE DT_RTLOT_TOOL_PORT_RULE (
    RULE_ID          NUMBER NOT NULL,
    TOOL_ID          VARCHAR2(64) NOT NULL,
    PORT_ID          VARCHAR2(32) NOT NULL,
    PORT_ROLE        VARCHAR2(16) NOT NULL,
    LOT_KEY_MODE     VARCHAR2(32) DEFAULT 'SINGLE_LOT_PER_PORT' NOT NULL,
    ENABLED_FLAG     CHAR(1) DEFAULT 'Y' NOT NULL,
    UPDATED_TS_UTC   TIMESTAMP(6) NOT NULL,
    CONSTRAINT PK_DT_RTLOT_TOOL_PORT_RULE PRIMARY KEY (RULE_ID)
);

ALTER TABLE DT_RTLOT_TOOL_PORT_RULE ADD (
    CONSTRAINT UQ_DT_RTLOT_PORT_RULE
    UNIQUE (TOOL_ID, PORT_ID)
);

ALTER TABLE DT_RTLOT_TOOL_PORT_RULE ADD (
    CONSTRAINT CK_DT_RTLOT_PORT_ROLE
    CHECK (PORT_ROLE IN ('LOAD', 'UNLOAD', 'BOTH'))
);

ALTER TABLE DT_RTLOT_TOOL_PORT_RULE ADD (
    CONSTRAINT CK_DT_RTLOT_PORT_LOT_MODE
    CHECK (LOT_KEY_MODE IN ('SINGLE_LOT_PER_PORT', 'MULTI_LOT_PER_PORT'))
);

ALTER TABLE DT_RTLOT_TOOL_PORT_RULE ADD (
    CONSTRAINT CK_DT_RTLOT_PORT_ENABLED
    CHECK (ENABLED_FLAG IN ('Y', 'N'))
);

COMMENT ON TABLE DT_RTLOT_TOOL_PORT_RULE IS '端口规则表：定义每台机台各 Port 的角色';
COMMENT ON COLUMN DT_RTLOT_TOOL_PORT_RULE.PORT_ROLE IS '端口角色：LOAD/UNLOAD/BOTH';

-- ============================================
-- 3. DT_RTLOT_EVENT_RULE 事件规则表
-- ============================================
CREATE TABLE DT_RTLOT_EVENT_RULE (
    RULE_ID              NUMBER NOT NULL,
    TOOL_ID              VARCHAR2(64) NOT NULL,
    EVENT_NAME           VARCHAR2(64) NOT NULL,
    ACTION_TYPE          VARCHAR2(16) NOT NULL,
    APPLY_PORT_ROLE      VARCHAR2(16) DEFAULT 'BOTH' NOT NULL,
    REQUIRE_PORT_ID      CHAR(1) DEFAULT 'Y' NOT NULL,
    ENABLED_FLAG         CHAR(1) DEFAULT 'Y' NOT NULL,
    PRIORITY_NO          NUMBER DEFAULT 100 NOT NULL,
    UPDATED_TS_UTC       TIMESTAMP(6) NOT NULL,
    CONSTRAINT PK_DT_RTLOT_EVENT_RULE PRIMARY KEY (RULE_ID)
);

ALTER TABLE DT_RTLOT_EVENT_RULE ADD (
    CONSTRAINT CK_DT_RTLOT_RULE_FLAGS
    CHECK (REQUIRE_PORT_ID IN ('Y', 'N') AND ENABLED_FLAG IN ('Y', 'N'))
);

ALTER TABLE DT_RTLOT_EVENT_RULE ADD (
    CONSTRAINT CK_DT_RTLOT_APPLY_PORT_ROLE
    CHECK (APPLY_PORT_ROLE IN ('LOAD', 'UNLOAD', 'BOTH'))
);

COMMENT ON TABLE DT_RTLOT_EVENT_RULE IS '事件规则表：定义事件如何更新 Lot 状态';
COMMENT ON COLUMN DT_RTLOT_EVENT_RULE.ACTION_TYPE IS '动作类型：START/UPDATE/END';
COMMENT ON COLUMN DT_RTLOT_EVENT_RULE.APPLY_PORT_ROLE IS '应用端口角色：LOAD/UNLOAD/BOTH';
COMMENT ON COLUMN DT_RTLOT_EVENT_RULE.PRIORITY_NO IS '优先级（小数优先）';

COMMIT;
