-- 查找所有非系统 schema 的表
SET LINESIZE 200
SET PAGESIZE 200

-- CDB root 层
SELECT owner, table_name, num_rows
FROM cdb_tables
WHERE owner NOT IN (
  'SYS','SYSTEM','DBSNMP','APPQOSSYS','DBSFWUSER','ORACLE_OCM',
  'OUTLN','REMOTE_SCHEDULER','SYSBACKUP','SYSDG','SYSKM','SYSRAC',
  'GSMADMIN_INTERNAL','GSMCATUSER','GSMUSER','ANONYMOUS','APEX_PUBLIC_USER',
  'APEX_INSTANCE_ADMIN','FLOWS_FILES','ORDDATA','ORDPLUGINS','ORDSYS',
  'SI_INFORMTN_SCHEMA','WMSYS','XDB','AUDSYS','CTXSYS','DVSYS','GGSYS',
  'GSMROOTUSER','MDDATA','MDSYS','OJVMSYS','OLAPSYS','LBACSYS','DIP',
  'SYS$UMF','SPATIAL_WFS_ADMIN_USR','SPATIAL_CSW_ADMIN_USR','DVF'
)
ORDER BY owner, table_name;

EXIT;
