-- 列出所有非系统用户及其表
SET LINESIZE 200
SET PAGESIZE 100

SELECT username, account_status, default_tablespace
FROM dba_users
WHERE username NOT IN (
  'SYS','SYSTEM','DBSNMP','APPQOSSYS','DBSFWUSER','ORACLE_OCM',
  'OUTLN','REMOTE_SCHEDULER','SYSBACKUP','SYSDG','SYSKM','SYSRAC',
  'GSMADMIN_INTERNAL','GSMCATUSER','GSMUSER','ANONYMOUS','APEX_PUBLIC_USER',
  'APEX_INSTANCE_ADMIN','FLOWS_FILES','ORDDATA','ORDPLUGINS','ORDSYS',
  'SI_INFORMTN_SCHEMA','WMSYS','XDB','XS$NULL','AUDSYS','DGPGQ_INT',
  'DVF','LBACSYS','REMOTE_SCHEDULER_AGENT','ROL1SEXT','R1SEXTADMIN',
  'SPATIAL_WFS_ADMIN_USR','SPATIAL_CSW_ADMIN_USR','DIP','TSQS_EXTADMIN'
)
ORDER BY username;

-- 各 PDB
SELECT name, open_mode FROM v$pdbs ORDER BY name;

EXIT;
