CREATE TABLE EMUUSER.DT_EVENT_REALTIMELOT (
    RT_ID NUMBER NOT NULL,
    TOOL_ID VARCHAR2(64 BYTE) NOT NULL,
    PORT_ID VARCHAR2(32 BYTE) NOT NULL,
    LOT_KEY_MODE VARCHAR2(32 BYTE) DEFAULT 'SINGLE_LOT_PER_PORT' NOT NULL,
    LOT_BIZ_KEY VARCHAR2(256 BYTE) NOT NULL,
    LOT_ID VARCHAR2(128 BYTE) NULL,
    BATCH_ID VARCHAR2(128 BYTE) NULL,
    CASSETTE_ID VARCHAR2(128 BYTE) NULL,
    SMIF_ID VARCHAR2(64 BYTE) NULL,
    WAFER_MAPPING CLOB NULL,
    WAFER_ID VARCHAR2(128 BYTE) NULL,
    LAST_EVENT_NAME VARCHAR2(64 BYTE) NOT NULL,
    LAST_EVENT_TS_UTC TIMESTAMP(6) NULL,
    START_TS_UTC TIMESTAMP(6) NULL,
    UPDATED_TS_UTC TIMESTAMP(6) NOT NULL,
    SOURCE_SYSTEM VARCHAR2(32 BYTE) NOT NULL,
    SOURCE_MESSAGE_ID VARCHAR2(128 BYTE) NOT NULL,
    ACTIVE_FLAG CHAR(1 BYTE) DEFAULT 'Y' NOT NULL,
    PRIMARY KEY(RT_ID) NOT DEFERRABLE USING INDEX TABLESPACE APC_DAT01 VALIDATE
) TABLESPACE APC_DAT01
  NOCOMPRESS PCTFREE 10 INITRANS 1 MAXTRANS 255
  STORAGE( INITIAL 4194304 NEXT 4194304 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 BUFFER_POOL DEFAULT )
  NOPARALLEL LOGGING NOCACHE MONITORING NOROWDEPENDENCIES DISABLE ROW MOVEMENT
  LOB (WAFER_MAPPING) STORE AS BASICFILE (
      TABLESPACE APC_DAT01 ENABLE STORAGE IN ROW CHUNK 8192 RETENTION NOCACHE LOGGING
  )
GO

ALTER TABLE EMUUSER.DT_EVENT_REALTIMELOT ADD (
    CONSTRAINT UQ_DT_RTLOT_TOOL_PORT_LOTKEY UNIQUE (TOOL_ID, PORT_ID, LOT_BIZ_KEY)
    NOT DEFERRABLE INITIALLY IMMEDIATE USING INDEX TABLESPACE APC_DAT01 VALIDATE
)
GO

ALTER TABLE EMUUSER.DT_EVENT_REALTIMELOT ADD (
    CONSTRAINT CK_DT_RTLOT_KEY_MODE CHECK (LOT_KEY_MODE IN ('SINGLE_LOT_PER_PORT', 'MULTI_LOT_PER_PORT'))
    NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE
)
GO

ALTER TABLE EMUUSER.DT_EVENT_REALTIMELOT ADD (
    CONSTRAINT CK_DT_RTLOT_ACTIVE CHECK (ACTIVE_FLAG IN ('Y', 'N'))
    NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE
)
GO

CREATE INDEX EMUUSER.IDX_DT_RTLOT_TOOL_PORT_ACTIVE
    ON EMUUSER.DT_EVENT_REALTIMELOT(TOOL_ID, PORT_ID, ACTIVE_FLAG)
    VISIBLE TABLESPACE APC_DAT01 NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE( INITIAL 4194304 NEXT 4194304 MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
    NOPARALLEL LOGGING
GO

CREATE INDEX EMUUSER.IDX_DT_RTLOT_TOOL_BATCH_ACTIVE
    ON EMUUSER.DT_EVENT_REALTIMELOT(TOOL_ID, BATCH_ID, ACTIVE_FLAG)
    VISIBLE TABLESPACE APC_DAT01 NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE( INITIAL 4194304 NEXT 4194304 MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
    NOPARALLEL LOGGING
GO

CREATE INDEX EMUUSER.IDX_DT_RTLOT_TOOL_ACTIVE
    ON EMUUSER.DT_EVENT_REALTIMELOT(TOOL_ID, ACTIVE_FLAG)
    VISIBLE TABLESPACE APC_DAT01 NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE( INITIAL 4194304 NEXT 4194304 MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
    NOPARALLEL LOGGING
GO

CREATE INDEX EMUUSER.IDX_DT_RTLOT_LOT
    ON EMUUSER.DT_EVENT_REALTIMELOT(LOT_ID)
    VISIBLE TABLESPACE APC_DAT01 NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE( INITIAL 4194304 NEXT 4194304 MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
    NOPARALLEL LOGGING
GO

CREATE OR REPLACE TRIGGER EMUUSER.TRG_DT_EVENT_REALTIMELOT_BI
BEFORE INSERT ON EMUUSER.DT_EVENT_REALTIMELOT
FOR EACH ROW
WHEN (NEW.RT_ID IS NULL)
BEGIN
    SELECT EMUUSER.SEQ_DT_EVENT_REALTIMELOT.NEXTVAL INTO :NEW.RT_ID FROM DUAL;
END;
GO
