CREATE TABLE EMUUSER.DT_RTLOT_EVENT_RULE (
    RULE_ID NUMBER NOT NULL,
    TOOL_ID VARCHAR2(64 BYTE) NOT NULL,
    EVENT_NAME VARCHAR2(64 BYTE) NOT NULL,
    ACTION_TYPE VARCHAR2(16 BYTE) NOT NULL,
    APPLY_PORT_ROLE VARCHAR2(16 BYTE) DEFAULT 'BOTH' NOT NULL,
    REQUIRE_PORT_ID CHAR(1 BYTE) DEFAULT 'Y' NOT NULL,
    ENABLED_FLAG CHAR(1 BYTE) DEFAULT 'Y' NOT NULL,
    PRIORITY_NO NUMBER DEFAULT 100 NOT NULL,
    UPDATED_TS_UTC TIMESTAMP(6) NOT NULL,
    PRIMARY KEY(RULE_ID) NOT DEFERRABLE USING INDEX TABLESPACE APC_DAT01 VALIDATE
) TABLESPACE APC_DAT01
  NOCOMPRESS PCTFREE 10 INITRANS 1 MAXTRANS 255
  STORAGE( INITIAL 4194304 NEXT 4194304 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 BUFFER_POOL DEFAULT )
  NOPARALLEL LOGGING NOCACHE MONITORING NOROWDEPENDENCIES DISABLE ROW MOVEMENT
GO

ALTER TABLE EMUUSER.DT_RTLOT_EVENT_RULE ADD (
    CONSTRAINT CK_DT_RTLOT_RULE_FLAGS CHECK (REQUIRE_PORT_ID IN ('Y', 'N') AND ENABLED_FLAG IN ('Y', 'N'))
    NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE
)
GO

ALTER TABLE EMUUSER.DT_RTLOT_EVENT_RULE ADD (
    CONSTRAINT CK_DT_RTLOT_APPLY_PORT_ROLE CHECK (APPLY_PORT_ROLE IN ('LOAD', 'UNLOAD', 'BOTH'))
    NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE
)
GO

ALTER TABLE EMUUSER.DT_RTLOT_EVENT_RULE ADD (
    CONSTRAINT CK_DT_RTLOT_ACTION_TYPE CHECK (ACTION_TYPE IN ('OPEN', 'UPDATE', 'CLEAR', 'IGNORE'))
    NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE
)
GO

CREATE INDEX EMUUSER.IDX_DT_RTLOT_EVENT_RULE
    ON EMUUSER.DT_RTLOT_EVENT_RULE(TOOL_ID, EVENT_NAME, ENABLED_FLAG, PRIORITY_NO)
    VISIBLE TABLESPACE APC_DAT01 NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE( INITIAL 4194304 NEXT 4194304 MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 BUFFER_POOL DEFAULT )
    NOPARALLEL LOGGING
GO

CREATE OR REPLACE TRIGGER EMUUSER.TRG_DT_RTLOT_EVENT_RULE_BI
BEFORE INSERT ON EMUUSER.DT_RTLOT_EVENT_RULE
FOR EACH ROW
WHEN (NEW.RULE_ID IS NULL)
BEGIN
    SELECT EMUUSER.SEQ_DT_RTLOT_EVENT_RULE.NEXTVAL INTO :NEW.RULE_ID FROM DUAL;
END;
GO
