CREATE TABLE EMUUSER.DT_RTLOT_TOOL_PORT_RULE (
    RULE_ID NUMBER NOT NULL,
    TOOL_ID VARCHAR2(64 BYTE) NOT NULL,
    PORT_ID VARCHAR2(32 BYTE) NOT NULL,
    PORT_ROLE VARCHAR2(16 BYTE) NOT NULL,
    LOT_KEY_MODE VARCHAR2(32 BYTE) DEFAULT 'SINGLE_LOT_PER_PORT' NOT NULL,
    ENABLED_FLAG CHAR(1 BYTE) DEFAULT 'Y' NOT NULL,
    UPDATED_TS_UTC TIMESTAMP(6) NOT NULL,
    PRIMARY KEY(RULE_ID) NOT DEFERRABLE USING INDEX TABLESPACE APC_DAT01 VALIDATE
) TABLESPACE APC_DAT01
  NOCOMPRESS PCTFREE 10 INITRANS 1 MAXTRANS 255
  STORAGE( INITIAL 4194304 NEXT 4194304 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 BUFFER_POOL DEFAULT )
  NOPARALLEL LOGGING NOCACHE MONITORING NOROWDEPENDENCIES DISABLE ROW MOVEMENT
GO

ALTER TABLE EMUUSER.DT_RTLOT_TOOL_PORT_RULE ADD (
    CONSTRAINT UQ_DT_RTLOT_PORT_RULE UNIQUE (TOOL_ID, PORT_ID)
    NOT DEFERRABLE INITIALLY IMMEDIATE USING INDEX TABLESPACE APC_DAT01 VALIDATE
)
GO

ALTER TABLE EMUUSER.DT_RTLOT_TOOL_PORT_RULE ADD (
    CONSTRAINT CK_DT_RTLOT_PORT_ROLE CHECK (PORT_ROLE IN ('LOAD', 'UNLOAD', 'BOTH'))
    NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE
)
GO

ALTER TABLE EMUUSER.DT_RTLOT_TOOL_PORT_RULE ADD (
    CONSTRAINT CK_DT_RTLOT_PORT_LOT_MODE CHECK (LOT_KEY_MODE IN ('SINGLE_LOT_PER_PORT', 'MULTI_LOT_PER_PORT'))
    NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE
)
GO

ALTER TABLE EMUUSER.DT_RTLOT_TOOL_PORT_RULE ADD (
    CONSTRAINT CK_DT_RTLOT_PORT_ENABLED CHECK (ENABLED_FLAG IN ('Y', 'N'))
    NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE
)
GO

CREATE OR REPLACE TRIGGER EMUUSER.TRG_DT_RTLOT_PORT_RULE_BI
BEFORE INSERT ON EMUUSER.DT_RTLOT_TOOL_PORT_RULE
FOR EACH ROW
WHEN (NEW.RULE_ID IS NULL)
BEGIN
    SELECT EMUUSER.SEQ_DT_RTLOT_TOOL_PORT_RULE.NEXTVAL INTO :NEW.RULE_ID FROM DUAL;
END;
GO
