/* ================================================================
   FabTwin DT 表建表脚本（依据 backend/models.py ORM 定义）
   生成时间: 2026-09-10
   说明:
     - 5 张 DT 表：dt_event_raw / dt_event_raw_cur / dt_event_std
       / dt_state_snapshot / dt_alarm_event
     - 这些表在量产环境由量产系统管理，本机测试时需手动建表
     - init_oracle_db.sql 不包含这些表
   ================================================================ */

SET DEFINE OFF
SET SQLBLANKLINES ON

-- 清理旧表（如存在）
DROP TABLE DT_ALARM_EVENT CASCADE CONSTRAINTS PURGE;
DROP TABLE DT_STATE_SNAPSHOT CASCADE CONSTRAINTS PURGE;
DROP TABLE DT_EVENT_STD CASCADE CONSTRAINTS PURGE;
DROP TABLE DT_EVENT_RAW_CUR CASCADE CONSTRAINTS PURGE;
DROP TABLE DT_EVENT_RAW CASCADE CONSTRAINTS PURGE;

-- ============================================
-- 1. DT_EVENT_RAW 原始事件表
-- ============================================
CREATE TABLE DT_EVENT_RAW (
    RAW_ID            VARCHAR2(255) NOT NULL,
    TOOL_ID           VARCHAR2(255) NOT NULL,
    SOURCE_SYSTEM     VARCHAR2(255) NOT NULL,
    SOURCE_MESSAGE_ID VARCHAR2(255) NOT NULL,
    RECEIVED_TS_UTC  VARCHAR2(255),
    EVENT_TS_UTC      VARCHAR2(255),
    PAYLOAD_JSON      CLOB,
    PARSE_STATUS      VARCHAR2(255) DEFAULT 'NEW',
    ERROR_MESSAGE     VARCHAR2(255),
    CONSTRAINT PK_DT_EVENT_RAW PRIMARY KEY (RAW_ID)
);
CREATE INDEX IDX_DT_EVENT_RAW_TOOL ON DT_EVENT_RAW (TOOL_ID);
CREATE INDEX IDX_DT_EVENT_RAW_RECV ON DT_EVENT_RAW (RECEIVED_TS_UTC);

-- ============================================
-- 2. DT_EVENT_RAW_CUR 当前状态表（每台机台最新一条）
-- ============================================
CREATE TABLE DT_EVENT_RAW_CUR (
    TOOL_ID           VARCHAR2(255) NOT NULL,
    RAW_ID            VARCHAR2(255),
    SOURCE_SYSTEM     VARCHAR2(255) NOT NULL,
    SOURCE_MESSAGE_ID VARCHAR2(255) NOT NULL,
    RECEIVED_TS_UTC  VARCHAR2(255),
    EVENT_TS_UTC      VARCHAR2(255),
    PAYLOAD_JSON      CLOB,
    PARSE_STATUS      VARCHAR2(255) DEFAULT 'NEW',
    ERROR_MESSAGE     VARCHAR2(255),
    CONSTRAINT PK_DT_EVENT_RAW_CUR PRIMARY KEY (TOOL_ID)
);
CREATE INDEX IDX_DT_EVENT_RAW_CUR_RECV ON DT_EVENT_RAW_CUR (RECEIVED_TS_UTC);

-- ============================================
-- 3. DT_EVENT_STD 标准化事件表
-- ============================================
CREATE TABLE DT_EVENT_STD (
    EVENT_ID          VARCHAR2(255) NOT NULL,
    RAW_ID            VARCHAR2(255),
    TOOL_ID           VARCHAR2(255) NOT NULL,
    EVENT_TYPE        VARCHAR2(255) NOT NULL,
    MACHINE_STATE     VARCHAR2(255),
    LOT_ID            VARCHAR2(255),
    RECIPE_ID         VARCHAR2(255),
    POD_POSITION      VARCHAR2(255),
    NORMALIZED_JSON   CLOB,
    CREATED_TS_UTC    VARCHAR2(255),
    CONSTRAINT PK_DT_EVENT_STD PRIMARY KEY (EVENT_ID)
);
CREATE INDEX IDX_DT_EVENT_STD_RAW ON DT_EVENT_STD (RAW_ID);
CREATE INDEX IDX_DT_EVENT_STD_TOOL ON DT_EVENT_STD (TOOL_ID);
CREATE INDEX IDX_DT_EVENT_STD_LOT ON DT_EVENT_STD (LOT_ID);

-- ============================================
-- 4. DT_STATE_SNAPSHOT 状态快照表
-- ============================================
CREATE TABLE DT_STATE_SNAPSHOT (
    SNAPSHOT_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TOOL_ID            VARCHAR2(255) NOT NULL,
    SNAPSHOT_TS_UTC    VARCHAR2(255) NOT NULL,
    MACHINE_STATE      VARCHAR2(255),
    MACHINE_MODE       VARCHAR2(255),
    CURRENT_ALARM_CODE VARCHAR2(255),
    CURRENT_LOT_ID     VARCHAR2(255),
    POD_POSITION       VARCHAR2(255),
    SNAPSHOT_JSON      CLOB
);
CREATE INDEX IDX_DT_STATE_SNAPSHOT_TOOL ON DT_STATE_SNAPSHOT (TOOL_ID);
CREATE INDEX IDX_DT_STATE_SNAPSHOT_TS ON DT_STATE_SNAPSHOT (SNAPSHOT_TS_UTC);

-- ============================================
-- 5. DT_ALARM_EVENT 告警事件表
-- ============================================
CREATE TABLE DT_ALARM_EVENT (
    ALARM_EVENT_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TOOL_ID             VARCHAR2(255) NOT NULL,
    ALARM_CODE          VARCHAR2(255) NOT NULL,
    ALARM_SEVERITY      VARCHAR2(255) NOT NULL,
    START_TS_UTC        VARCHAR2(255) NOT NULL,
    END_TS_UTC          VARCHAR2(255),
    DURATION_SEC        FLOAT,
    CYCLE_ID            VARCHAR2(255),
    LOT_ID              VARCHAR2(255),
    SOURCE_EVENT_START_ID VARCHAR2(255),
    SOURCE_EVENT_END_ID   VARCHAR2(255),
    ALARM_CONTEXT_JSON  CLOB
);
CREATE INDEX IDX_DT_ALARM_EVENT_TOOL ON DT_ALARM_EVENT (TOOL_ID);
CREATE INDEX IDX_DT_ALARM_EVENT_START ON DT_ALARM_EVENT (START_TS_UTC);
CREATE INDEX IDX_DT_ALARM_EVENT_LOT ON DT_ALARM_EVENT (LOT_ID);

COMMIT;
